apiVersion: apps/v1
kind: Deployment
metadata:
  name: leed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leed
  template:
    metadata:
      labels:
        app: leed
    spec:
      containers:
      - name: leed
        image: edouard071203/image_leed
        ports:
        - containerPort: 3000
