version: "3"

services:
  leed_server:
    image: php_apache:latest
    ports:
      - ${LEED_APP_PORT}:80

  leed_mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
