apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql  # Label ajouté
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "a"
        - name: MYSQL_DATABASE
          value: "leed_a"
        - name: MYSQL_USER
          value: "a"
        - name: MYSQL_PASSWORD
          value: "a"
      ports:
        - containerPort: 3306
