apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql  # Le label que vous appliquerez à votre Pod MySQL
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
