#!/bin/bash

echo
echo "Projet DevOps (https://github.com/Licouu/projetdevops/)"
echo

# lancement de minikube
if ! command -v minikube 2>&1 > /dev/null
then
	echo "[E] minikube n'est pas installé !"
	exit 1
else
	echo "[I] minikube est présent"
	if [[ -z $(minikube status | grep "host: Running") ]]
	then
		echo "[W] minikube n'est pas démarré"
		echo "[I] Démarrage..."
		minikube start 2>&1 > /dev/null
		echo "[I] minikube a été démarré"
	else
		echo "[I] minikube est déjà démarré"
	fi
fi

sudo mkdir -p /tmp/hostpath-provisioner/default/grafana-data && \
sudo chown -R 1000:1000 /tmp/hostpath-provisioner/default/grafana-data && \
sudo chmod -R 755 /tmp/hostpath-provisioner/default/grafana-data

# lancement de leed
echo "[I] Démarrage de Leed..."

kubectl apply -f mysql-pod.yml
kubectl apply -f mysql-service.yml
kubectl apply -f web-app-deployement.yml
kubectl apply -f leed-service.yml

echo "[I] Démarrage de Prometheus..."

kubectl apply -f prom-grafana/kube-supp/prometheus-cm0-configmap.yaml
kubectl apply -f prom-grafana/kube-supp/prometheus-deployment.yaml
kubectl apply -f prom-grafana/kube-supp/prometheus-service.yaml

echo "[I] Démarrage de Grafana..."

kubectl apply -f prom-grafana/kube-supp/grafana-cm1-configmap.yaml
kubectl apply -f prom-grafana/kube-supp/grafana-cm2-configmap.yaml
kubectl apply -f prom-grafana/kube-supp/grafana-data-persistentvolumeclaim.yaml
kubectl apply -f prom-grafana/kube-supp/grafana-data-pv.yaml
kubectl apply -f prom-grafana/kube-supp/grafana-deployment.yaml
kubectl apply -f prom-grafana/kube-supp/grafana-service.yaml

echo "[I] Leed a été lancé à http://$(kubectl get nodes -o wide | grep minikube | cut -d " " -f 17):31117/"
echo "[I] Prometheus a été lancé à http://$(kubectl get nodes -o wide | grep minikube | cut -d " " -f 17):31111/"
echo "[I] Grafana a été lancé à http://$(kubectl get nodes -o wide | grep minikube | cut -d " " -f 17):30001/"
