apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1  # Max 1 pod indisponible pendant la mise à jour
        maxSurge: 1 
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app-container
        image: edouard071203/image_leed
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_DATABASE
          value: leed_a
        - name: MYSQL_USER
          value: a
        - name: MYSQL_PASSWORD
          value: a

