apiVersion: v1
data:
  prometheus.yml: |
    # my global config
    global:
      scrape_interval:     5s
      evaluation_interval: 5s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:

    rule_files:

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090'] # ip du serveur (ou localhost?)

      - job_name: 'cadvisor'
        static_configs:
        - targets: ['localhost:8081'] # ip du cluster où y a l'appli web

      # Nouveau job pour surveiller le conteneur "dummy"
      #- job_name: 'dummy'
      #  static_configs:
      #  - targets: ['dummy:8080']

    # Ajouter des "-job_name" pour chaque pod/conteneur
      - job_name: 'leed'
        static_configs:
        - targets: ['172.27.204.192:31007']

    remote_write:
      - url: 'http://localhost:3000'
        basic_auth:
          username: admin
          password: pass
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
