# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090'] # ip du serveur (ou localhost?)

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8081'] # ip du cluster où y a l'appli web

  # Nouveau job pour surveiller le conteneur "dummy"
  #- job_name: 'dummy'
  #  static_configs:
  #  - targets: ['dummy:8080']

# Ajouter des "-job_name" pour chaque pod/conteneur
